from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any


WE_COM_MENTION_RE = re.compile(r"^\s*@\S+\s*")


@dataclass(frozen=True)
class WeComTurn:
    session_id: str
    message: str
    metadata: dict[str, Any]


@dataclass(frozen=True)
class WeComFeedback:
    assistant_message_id: str | None
    stream_id: str | None
    session_id: str
    rating: str | None
    reason: str | None
    metadata: dict[str, Any]


def strip_wecom_mention(content: str) -> str:
    """企业微信群聊会带 @机器人 前缀，内部对话只保留真实问题。"""
    return WE_COM_MENTION_RE.sub("", content, count=1).strip()


def build_wecom_turn(payload: dict[str, Any]) -> WeComTurn:
    body = payload.get("body", payload)
    sender = body.get("from") or {}
    userid = str(sender.get("userid") or "").strip()
    if not userid:
        raise ValueError("from.userid is required")

    msgtype = str(body.get("msgtype") or "text")
    if msgtype != "text":
        raise ValueError("only text msgtype is supported")

    text = body.get("text") or {}
    message = strip_wecom_mention(str(text.get("content") or ""))
    if not message:
        raise ValueError("text content is required")

    quote = body.get("quote") or {}
    quote_text = ""
    if quote.get("msgtype") == "text":
        quote_text = str((quote.get("text") or {}).get("content") or "").strip()
    if quote_text:
        message = f"{message}\n\n引用内容：{quote_text}"

    return WeComTurn(
        session_id=userid,
        message=message,
        metadata={
            "channel": "wecom",
            "transport": "websocket" if payload.get("cmd") else "http",
            "msgid": body.get("msgid"),
            "aibotid": body.get("aibotid"),
            "chatid": body.get("chatid"),
            "chattype": body.get("chattype"),
            "from_userid": userid,
            "response_url": body.get("response_url"),
            "msgtype": msgtype,
            "quote": quote or None,
            "ws_cmd": payload.get("cmd"),
            "ws_req_id": (payload.get("headers") or {}).get("req_id"),
        },
    )


def build_feedback_id(assistant_message_id: str | int | None) -> str | None:
    if assistant_message_id is None:
        return None
    return f"assistant_message:{assistant_message_id}"


def build_stream_feedback_id(stream_id: str | None) -> str | None:
    value = str(stream_id or "").strip()
    return f"wecom_stream:{value}" if value else None


def parse_feedback_id(feedback_id: str | None) -> str | None:
    value = str(feedback_id or "").strip()
    prefix = "assistant_message:"
    if not value.startswith(prefix):
        return None
    raw_id = value[len(prefix) :]
    return raw_id or None


def parse_stream_feedback_id(feedback_id: str | None) -> str | None:
    value = str(feedback_id or "").strip()
    prefix = "wecom_stream:"
    if not value.startswith(prefix):
        return None
    stream_id = value[len(prefix) :].strip()
    return stream_id or None


def build_wecom_feedback(payload: dict[str, Any]) -> WeComFeedback:
    body = payload.get("body", payload)
    sender = body.get("from") or {}
    userid = str(sender.get("userid") or "").strip()
    if not userid:
        raise ValueError("from.userid is required")

    event = body.get("event") or {}
    feedback_event = event.get("feedback_event") or {}
    raw_feedback_id = feedback_event.get("id")
    assistant_message_id = parse_feedback_id(raw_feedback_id)
    stream_id = parse_stream_feedback_id(raw_feedback_id)
    if assistant_message_id is None and stream_id is None:
        raise ValueError("feedback id is not generated by this service")

    feedback_type = feedback_event.get("type")
    rating = None
    if feedback_type == 1:
        rating = "positive"
    elif feedback_type == 2:
        rating = "negative"

    content = str(feedback_event.get("content") or "").strip()
    inaccurate_reason_list = feedback_event.get("inaccurate_reason_list") or []
    reason_parts = []
    if content:
        reason_parts.append(content)
    if inaccurate_reason_list:
        reason_parts.append(f"inaccurate_reason_list={inaccurate_reason_list}")

    return WeComFeedback(
        assistant_message_id=assistant_message_id,
        stream_id=stream_id,
        session_id=userid,
        rating=rating,
        reason="; ".join(reason_parts) or None,
        metadata={
            "channel": "wecom",
            "transport": "websocket" if payload.get("cmd") else "http",
            "msgid": body.get("msgid"),
            "aibotid": body.get("aibotid"),
            "chatid": body.get("chatid"),
            "chattype": body.get("chattype"),
            "from_userid": userid,
            "eventtype": event.get("eventtype"),
            "feedback_id": feedback_event.get("id"),
            "wecom_stream_id": stream_id,
            "feedback_type": feedback_type,
            "feedback_content": content or None,
            "inaccurate_reason_list": inaccurate_reason_list,
            "ws_cmd": payload.get("cmd"),
            "ws_req_id": (payload.get("headers") or {}).get("req_id"),
        },
    )


def format_answer_for_wecom(answer: str, assets: list[dict[str, Any]] | None = None) -> str:
    text = str(answer or "未生成回答").rstrip()
    assets = assets or []
    lines = [text]
    image_lines = []
    for asset in assets:
        platform = str(asset.get("platform") or "FAQ").strip() or "FAQ"
        url = str(asset.get("url") or "").strip()
        if url.startswith(("https://", "http://")):
            # 企业微信 Markdown 对外链图片兼容性不稳定，这里先发可点击链接。
            image_lines.append(f"- {platform} 操作图：{url}")
    if image_lines:
        lines.extend(["", "操作配图：", *image_lines])
    return "\n".join(lines)


def chunk_text(text: str, max_chars: int = 700) -> list[str]:
    value = str(text or "")
    if len(value) <= max_chars:
        return [value]
    chunks = []
    current = []
    current_len = 0
    for paragraph in value.splitlines(keepends=True):
        if current and current_len + len(paragraph) > max_chars:
            chunks.append("".join(current))
            current = []
            current_len = 0
        while len(paragraph) > max_chars:
            chunks.append(paragraph[:max_chars])
            paragraph = paragraph[max_chars:]
        current.append(paragraph)
        current_len += len(paragraph)
    if current:
        chunks.append("".join(current))
    return chunks or [value]
